name: flutter_input_example
description: Example to show all input fields together with some form logic
# version: 1.2.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_input:
    path: ../

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0

flutter:
  uses-material-design: true