name: flutter_input
description: This package provides widgets for input fields.
  Each widget can be used standalone or within a form.
homepage: https://github.com/djarjo/flutter_input
version: 1.0.1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  pedantic: ^1.8.0

dev_dependencies:
  dartdoc: '>=0.30.0'
  test: '>=1.9.4'
