name: flutter_input
description: This package provides widgets for input fields.
  Each widget can be used standalone or with the integrated form.
homepage: https://github.com/djarjo/flutter_input
version: 1.2.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  i18n_extension: ^1.3.5
  intl: ^0.16.0
  pedantic: ^1.9.0

dev_dependencies:
  dartdoc: ^0.30.4
  test: ^1.14.2

flutter:
  assets:
    - lib/assets/flags/
